version: 1
disable_existing_loggers: False
formatters:
  default:
    "()": uvicorn.logging.DefaultFormatter
    fmt: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  default:
    level: INFO
    formatter: default
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn:
    handlers: [default]
    level: INFO
  uvicorn.error:
    handlers: [default]
    level: INFO
    propagate: False
  uvicorn.access:
    handlers: [default]
    level: INFO
    propagate: False